swagger: '2.0'
info:
  title: MCP Toolbox BigQuery API
  description: API Gateway for MCP Toolbox with BigQuery access
  version: '1.0.0'

host: mcp-toolbox-gateway-2fbutm4xoa-an.a.run.app
schemes:
  - https

x-google-backend:
  address: https://mcp-toolbox-2fbutm4xoa-an.a.run.app
  protocol: h2

securityDefinitions:
  api_key:
    type: apiKey
    name: X-API-Key
    in: header

security:
  - api_key: []

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      security: []  # No auth required for health check
      responses:
        '200':
          description: Service is healthy
          schema:
            type: string
      x-google-backend:
        address: https://mcp-toolbox-2fbutm4xoa-an.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS

  /mcp:
    post:
      summary: MCP endpoint for BigQuery operations
      operationId: mcpEndpoint
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
      responses:
        '200':
          description: Successful MCP response
          schema:
            type: object
        '401':
          description: Unauthorized - Invalid or missing API key
        '400':
          description: Bad request
        '500':
          description: Internal server error
      x-google-backend:
        address: https://mcp-toolbox-2fbutm4xoa-an.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS

  /{path}:
    get:
      summary: Catch-all for other GET paths
      operationId: catchAllGet
      parameters:
        - name: path
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
      x-google-backend:
        address: https://mcp-toolbox-2fbutm4xoa-an.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
    
    post:
      summary: Catch-all for other POST paths
      operationId: catchAllPost
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - in: body
          name: body
          schema:
            type: object
      responses:
        '200':
          description: Success
          schema:
            type: object
      x-google-backend:
        address: https://mcp-toolbox-2fbutm4xoa-an.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS